<a href="https://colab.research.google.com/github/Atul57/Data-Science-project/blob/main/Manual_DC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
from google.colab import drive
drive.mount('/content/drive')
'/content/drive/MyDrive/cafe_sales_dirty.csv'

Mounted at /content/drive

'/content/drive/MyDrive/cafe_sales_dirty.csv'

In [ ]:
# Load
df = pd.read_csv('/content/drive/MyDrive/cafe_sales_dirty.csv')
df.head()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11

In [ ]:
# Check Datatype
df.dtypes

Transaction ID      object
Item                object
Quantity            object
Price Per Unit      object
Total Spent         object
Payment Method      object
Location            object
Transaction Date    object
dtype: object

In [ ]:
# Convert to numeric
# df['Quantity'] = pd.to_numeric(df['Quantity'], errors='coerce')
df['Quantity'] = df['Quantity'].fillna(0).astype(int)
df['Price Per Unit'] = pd.to_numeric(df['Price Per Unit'], errors='coerce')
df['Total Spent'] = pd.to_numeric(df['Total Spent'], errors='coerce')
df['Transaction Date'] = pd.to_datetime(df['Transaction Date'], errors='coerce')
df.dtypes

Transaction ID              object
Item                        object
Quantity                     int64
Price Per Unit             float64
Total Spent                float64
Payment Method              object
Location                    object
Transaction Date    datetime64[ns]
dtype: object

In [ ]:
# Find Missing values
df.isnull().sum()

Transaction ID      0
Item                0
Quantity            0
Price Per Unit      0
Total Spent         0
Payment Method      0
Location            0
Transaction Date    0
dtype: int64

In [ ]:
# Filling Missing values
df['Quantity'] = df['Quantity'].fillna(df['Quantity'].mean())
df['Price Per Unit'] = df['Price Per Unit'].fillna(df['Price Per Unit'].mean())
df['Total Spent'] = df['Total Spent'].fillna(df['Total Spent'].mean())

In [ ]:
df.isnull().sum()

Transaction ID      0
Item                0
Quantity            0
Price Per Unit      0
Total Spent         0
Payment Method      0
Location            0
Transaction Date    0
dtype: int64

In [ ]:
# Replacing ERROR with Unknown
df.replace(['ERROR','Unknown'], pd.NA, inplace=True)

In [ ]:
# Filling values into items
mode_item = df['Item'].mode()[0]
df['Item'] = df['Item'].replace('Unknown' and 'UNKNOWN', np.nan)
df['Item'] = df['Item'].fillna(mode_item)

In [ ]:
# Filling values into Payment Method
mode_pm = df['Payment Method'].mode()[0]
df['Payment Method'] = df['Payment Method'].replace('Unknown' and 'UNKNOWN', np.nan)
df['Payment Method'] = df['Payment Method'].fillna(mode_pm)

In [ ]:
# Filling missing values in location
mode_location = df['Location'].mode()[0]
df['Location'] = df['Location'].replace('Unknown' and 'UNKNOWN', np.nan)
df['Location'] = df['Location'].fillna(mode_location)

In [ ]:
df.head()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.000000,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.000000,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,8.924352,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.000000,Digital Wallet,Takeaway,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.000000,Digital Wallet,In-store,2023-06-11

In [ ]:

# Checking Null values
df.isnull().sum()

Transaction ID      0
Item                0
Quantity            0
Price Per Unit      0
Total Spent         0
Payment Method      0
Location            0
Transaction Date    0
dtype: int64

In [ ]:
# Why meadian is used in Transaction date
dat = df['Transaction Date'].median()
df['Transaction Date'] = df['Transaction Date'].fillna(dat)
df.isnull().sum()

Transaction ID      0
Item                0
Quantity            0
Price Per Unit      0
Total Spent         0
Payment Method      0
Location            0
Transaction Date    0
dtype: int64

In [ ]:
# Check Duplicate Values
df.duplicated().sum()

np.int64(0)

In [ ]:
# Removing duplicate values
df = df.drop_duplicates()
df.duplicated().sum()

np.int64(0)

In [ ]:
#
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  object
 1   Item              10000 non-null  object
 2   Quantity          10000 non-null  int64
 3   Price Per Unit    10000 non-null  float64
 4   Total Spent       10000 non-null  float64
 5   Payment Method    10000 non-null  object
 6   Location          10000 non-null  object
 7   Transaction Date  10000 non-null  datetime64[ns]
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 625.1+ KB

In [ ]:
df.to_csv('new_cafe_sales_data.csv', index=False)
print("Data Cleaning completed!")

Data Cleaning completed!

# The 10 Business Questions & Answers

Q.1 Which item generated the highest revenue?

In [ ]:
df.groupby('Item')['Total Spent'].sum().sort_values(ascending=False).head(1)

Item
Juice    19069.981364
Name: Total Spent, dtype: float64

Q.2 Which location generated the most sales?

In [ ]:
df.groupby('Location')['Total Spent'].sum().sort_values(ascending=False)

Location
Takeaway    62016.720783
In-store    27226.804169
Name: Total Spent, dtype: float64

Q.3 Total revenue

In [ ]:
df['Total Spent'].sum()

np.float64(89243.52495262159)

Q.4 Most used payment method

In [ ]:
df['Payment Method'].value_counts()

Payment Method
Digital Wallet    5469
Credit Card       2273
Cash              2258
Name: count, dtype: int64

Q.5 Top 5 selling items

In [ ]:
df['Item'].value_counts().head()

Item
Juice       2140
Coffee      1165
Salad       1148
Cake        1139
Sandwich    1131
Name: count, dtype: int64

Q.6 Highest sales day

In [ ]:
df.groupby('Transaction Date')['Total Spent'].sum().sort_values(ascending=False).head(1)

Transaction Date
2023-07-02    4453.306222
Name: Total Spent, dtype: float64

Q.7 Average spending per transaction

In [ ]:
df['Total Spent'].mean()

np.float64(8.92435249526216)

Q.8 Item with highest average quantity sold

In [ ]:
df.groupby('Item')['Quantity'].mean().sort_values(ascending=False)

Item
Smoothie    3.059307
Coffee      3.048069
Tea         3.047750
Cake        3.043898
Sandwich    3.030946
Salad       3.021777
Juice       3.007009
Cookie      2.975275
Name: Quantity, dtype: float64

Q.9 Sales contribution by location (%)

In [ ]:
location_sales = df.groupby('Location')['Total Spent'].sum()
(location_sales / location_sales.sum()) * 100

Location
In-store    30.508437
Takeaway    69.491563
Name: Total Spent, dtype: float64

Q.10 Monthly sales trend

In [ ]:
df['Transaction Date'] = pd.to_datetime(df['Transaction Date'])
df.groupby(df['Transaction Date'].dt.month)['Total Spent'].sum()

Transaction Date
1      7264.444567
2      6616.352337
3      7241.444567
4      7185.641977
5      7004.201042
6      7357.079280
7     11143.855970
8      7136.033165
9      6867.398452
10     7370.701042
11     6925.171510
12     7131.201042
Name: Total Spent, dtype: float64